pipeline {
    agent {
        label 'new'
    }
    environment { 
        JAVA_HOME='/usr/lib/jvm/java-17-openjdk-17.0.11.0.9-2.el8.x86_64/bin/'
    }
    stages {
        stage('Test Java') {
            
            steps {
               
                sh 'java -version'
            }
        }
        stage('Build') {
            environment { 
                JAVA_HOME='/usr/lib/jvm/java-17-openjdk-17.0.11.0.9-2.el8.x86_64/bin/'
            }
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
